server:
  port: 3001
  servlet:
    context-path: /agentic-mcp-server
spring:
  application:
    name: agentic-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: agentic-mcp-server
        version: 1.0.0
        type: sync
        studio: false
        base-url: /agentic-mcp-server
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres #hackathon123
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: hackathon
    hibernate:
      ddl-auto: 'create-drop'
